BASIC:
  NODES: 1
  GPUS: 4
  NR: 0
  WORLD_SIZE: 4
  CHECK_EVERY_BATCH: 10
  DATASET: 'FGVCDataset'
  DATA_PATH: '/data/dataset/fungi2024'
  LOG_NAME: 'volo-openset-proser.log'
  MODEL:
    NAME: 'volo_d4_448'
    PRETRAIN_PATH: '/data/tbf/fungi/pretrain/new_volo_d4_448.pth'
    NUM_CLASS: 1604

TRAIN:
  BATCH_SIZE: 32
  AUG:
    IMG_SIZE: 448
    MEAN: [ 0.48145466, 0.4578275, 0.40821073 ]
    STD: [ 0.26862954, 0.26130258, 0.27577711 ]
  OPENSET:
    EPOCHS: 5
    C: 128
    TEMP: 1.0
    MIX:
      ALPHA: 0.4
    LOSS:
      NAME: 'ProserLoss'
    OPTIMIZER:
      NAME: 'SGD'
      PARAMS:
        lr: 1.0e-3
        momentum: 0.9
        weight_decay: 5.0e-4
    SCHEDULER:
      NAME: 'CosineAnnealingLR'
      PARAMS:
        T_max: 5
        eta_min: 0.5e-5

VALID:
  BATCH_SIZE: 256
  AUG:
    IMG_SIZE: 448
    MEAN: [ 0.48145466, 0.4578275, 0.40821073 ]
    STD: [ 0.26862954, 0.26130258, 0.27577711 ]